POST http://127.0.0.1:8000/login
Content-Type: application/json

{"username":"ze", "password":"password1234"}

###

POST http://127.0.0.1:8000/register
Content-Type: application/json

{"username":"ze", "password":"password1234", "email":"ze@sapo.pt"}

###

GET http://127.0.0.1:8000/test_token
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE2MDcyNTU5LCJpYXQiOjE3MTYwNzIyNTksImp0aSI6IjJmYzk3OTRkNzlmYzRjNzFiOTkyNDc1ZDUzZTAyZjYzIiwidXNlcl9pZCI6MSwiaWQiOjEsInVzZXJuYW1lIjoiemUiLCJlbWFpbCI6InplQHNhcG8ucHQifQ.LE9_Aep9x1-HwcMCOxDkhIBuIZU_fO7XOtgYOM2sez8

{}

###
GET http://127.0.0.1:8000/specialties
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE2MDcyNTU5LCJpYXQiOjE3MTYwNzIyNTksImp0aSI6IjJmYzk3OTRkNzlmYzRjNzFiOTkyNDc1ZDUzZTAyZjYzIiwidXNlcl9pZCI6MSwiaWQiOjEsInVzZXJuYW1lIjoiemUiLCJlbWFpbCI6InplQHNhcG8ucHQifQ.LE9_Aep9x1-HwcMCOxDkhIBuIZU_fO7XOtgYOM2sez8

{}

###
GET http://127.0.0.1:8000/doctors/Rehab
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE2MDcyNTU5LCJpYXQiOjE3MTYwNzIyNTksImp0aSI6IjJmYzk3OTRkNzlmYzRjNzFiOTkyNDc1ZDUzZTAyZjYzIiwidXNlcl9pZCI6MSwiaWQiOjEsInVzZXJuYW1lIjoiemUiLCJlbWFpbCI6InplQHNhcG8ucHQifQ.LE9_Aep9x1-HwcMCOxDkhIBuIZU_fO7XOtgYOM2sez8

{}